#!/bin/bash
read -p "Sisesta ridade arv: " read_ridade_arv
for (( i = 1; i <= read_ridade_arv; i++ ))
do
    echo -n "$i. "
    for (( j = 1; j <= read_ridade_arv - i; j++ ))
    do
        echo -n "o "
    done
    for (( j = 1; j <= i; j++ ))
    do
        echo -n "* "
    done
    
    echo ""
done

