#!/bin/bash
if [ $# -ne 1 ]; then
    echo "Käivita see skript koos arvuga, mille paarsust soovid kontrollida. Näiteks: $0 3"
else
    arv=$1
    # Kontrollime, kas argument on täisarv
    if ! [[ "$arv" =~ ^-?[0-9]+$ ]]; then
        echo "Sisesta palun täisarv."
        exit 1
    fi
    
    # Arvutame jäägi jagamisel kahega, et leida paarsus
    jaak=$(( arv % 2 ))
    if [ $jaak -eq 0 ]; then
        echo "Antud arv on paaris"
    else
        echo "Antud arv on paaritu"
    fi
fi
